import path from "path";
import type { NextConfig } from "next";

// This app builds to a STATIC EXPORT served by the fintok frontend from
// its public/projects/ folder — no server, no service. basePath
// is CRITICAL: it prefixes every route, asset (/projects/_next/...), and
// next/link href generated by this app so the proxy boundary is transparent.
const nextConfig: NextConfig = {
  basePath: "/projects",
  output: "export",
  // Pins the file-tracing root to this package regardless of stray
  // lockfiles elsewhere on the machine (e.g. a `package-lock.json` sitting
  // in the user's home directory) — without this, Next can infer the wrong
  // workspace root and nest `.next/standalone` several directories deeper
  // than `server.js` expects.
  outputFileTracingRoot: path.join(__dirname),
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
} as NextConfig;

export default nextConfig;
